const taskTypeCategories = {
  Coding: [
    "Sub-task Module",
    "Algorithmic",
    "Frontend",
    "Backend",
    "Machine Learning",
    "Scripting / Automation",
    "Database Querying",
    "API Integration",
    "Debugging / Testing",
  ],
  "Sheet-Based Tasks": [
    "Data Entry",
    "Analysis / Charts",
    "Pivot Tables",
    "Dashboard View",
    "Data Cleaning",
    "Formula Writing",
    "Conditional Formatting",
    "Financial Modelling",
  ],
  "Document-Based Tasks": [
    "Reports",
    "Documentation",
    "Meeting Notes",
    "Brainstorming / Idea Logs",
    "SOPs (Standard Operating Procedures)",
    "Research / Articles",
    "Writing Proposals",
  ],
  "Email-Based Tasks": [
    "Formal Communication",
    "Client / Stakeholder Updates",
    "Support / Ticket Handling",
    "Sales Outreach",
    "Follow-ups",
    "Internal Team Mails",
    "Newsletters",
    "HR / Onboarding Communication",
  ],
  "Task Management": [
    "Assign Tasks",
    "Track Progress",
    "Sprint Planning",
    "Bug / Issue Tracking",
    "Daily Standups",
    "Project Status Updates",
  ],
  "Design / Visual Tasks": [
    "Wireframes / Mockups",
    "Diagrams / Flowcharts",
    "Mindmaps",
    "Infographics",
    "UI/UX Design",
    "Branding Assets",
  ],
};

export {taskTypeCategories}